export const playerTexts = {
  "de": {
    "locale": "de",
    "pause": "Pause",
    "playerPlay": "Abspielen",
    "fullscreenUnavailable": "Vollbild ist nicht verfügbar",
    "pictureInPictureUnavailable": "Bild-in-Bild ist nicht verfügbar",
    "recordings": "VOD-Player",
    "loading": "Wird geladen",
    "exactTime": "Genaue Wiedergabezeit",
    "skipBack": "10 Sekunden zurück",
    "skipForward": "10 Sekunden vor",
    "volume": "Lautstärke",
    "volumePercent": "Lautstärke in Prozent",
    "playbackSpeed": "Wiedergabegeschwindigkeit",
    "cinema": "Kinomodus",
    "pictureInPicture": "Bild-in-Bild",
    "playbackOptions": "Weitere Wiedergabeoptionen",
    "resetRate": "1×",
    "categoryUnavailable": "Kategorie nicht erfasst",
    "fineSeekInstructions": "Nach oben ziehen für Feinmodus. Pfeiltasten: 1 Sekunde, mit Umschalt: 10 Sekunden. Escape: Auswahl verwerfen.",
    "playbackPosition": "Position im gesamten VOD",
    "historyEmptyTitle": "Kein Titel",
    "viewerMeasurementMissing": "Zuschauermessung fehlt",
    "viewerCount": "Zuschauer",
    "historyTitleUnknown": "Titel für diesen Zeitpunkt nicht erfasst",
    "viewerMeasuredAt": "Gemessen am",
    "exactTimeHint": "Stunden:Minuten:Sekunden,Millisekunden",
    "exactTimeInvalid": "Gültige Zeit innerhalb des VODs eingeben.",
    "close": "Schließen",
    "jumpToTime": "Zur Zeit springen",
    "mute": "Stummschalten",
    "unmute": "Ton einschalten",
    "fullscreen": "Vollbild",
    "exitFullscreen": "Vollbild beenden"
  },
  "en": {
    "locale": "en",
    "pause": "Pause",
    "playerPlay": "Play",
    "fullscreenUnavailable": "Fullscreen is unavailable",
    "pictureInPictureUnavailable": "Picture-in-picture is unavailable",
    "recordings": "VOD player",
    "loading": "Loading",
    "exactTime": "Exact playback time",
    "skipBack": "Back 10 seconds",
    "skipForward": "Forward 10 seconds",
    "volume": "Volume",
    "volumePercent": "Volume in percent",
    "playbackSpeed": "Playback speed",
    "cinema": "Cinema mode",
    "pictureInPicture": "Picture in picture",
    "playbackOptions": "More playback options",
    "resetRate": "1×",
    "categoryUnavailable": "Category not recorded",
    "fineSeekInstructions": "Drag upwards for fine seeking. Arrow keys: 1 second, with Shift: 10 seconds. Escape: cancel selection.",
    "playbackPosition": "Position in the full VOD",
    "historyEmptyTitle": "No title",
    "viewerMeasurementMissing": "Viewer measurement unavailable",
    "viewerCount": "viewers",
    "historyTitleUnknown": "Title not recorded for this time",
    "viewerMeasuredAt": "Measured at",
    "exactTimeHint": "Hours:minutes:seconds,milliseconds",
    "exactTimeInvalid": "Enter a valid time within the VOD.",
    "close": "Close",
    "jumpToTime": "Jump to time",
    "mute": "Mute",
    "unmute": "Unmute",
    "fullscreen": "Fullscreen",
    "exitFullscreen": "Exit fullscreen"
  }
};
